"""empty message

Revision ID: 64aa1e656a19
Revises: None
Create Date: 2016-03-09 12:42:33.703867

"""

# revision identifiers, used by Alembic.
revision = '64aa1e656a19'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noncontactmeeting')
    op.add_column('meeting', sa.Column('SM_typeMeeting', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'SM_typeMeeting')
    op.create_table('noncontactmeeting',
    sa.Column('NCM_idNonContactMeeting', sa.INTEGER(), nullable=False),
    sa.Column('NCM_challenges', sa.VARCHAR(length=300), nullable=True),
    sa.Column('NCM_planned', sa.VARCHAR(length=300), nullable=True),
    sa.Column('NCM_done', sa.VARCHAR(length=300), nullable=True),
    sa.Column('NCM_user', sa.VARCHAR(length=16), nullable=True),
    sa.ForeignKeyConstraint(['NCM_user'], ['equipo.EQ_username'], ),
    sa.PrimaryKeyConstraint('NCM_idNonContactMeeting')
    )
    ### end Alembic commands ###
